### ISSUE TITLE
提醒

### ISSUE THREAD

**Issue by Xyinkl** [rczhen/Recsys-Ads-Search-Papers#1]
https://www.google.com/maps/@39.9690192,116.3702856,3a,83.6y,229.84h,84.33t/data=!3m7!1e1!3m5!1sAF1QipON3QhjGSNpmfY0LJpM3C-7ZW7aWbjRAyzsSddC!2e10!3e12!7i12288!8i4286

偶然在街景看到的，就顺着ID找来了。

要是不小心传的，就删了吧。

**Comment by rczhen** [comment]
非常感谢，已处理。请问是怎么发现这个问题的呢，我好再看看有没有其它类似情况。谢谢，祝好~

**Comment by Xyinkl** [comment]
我在玩之前谷歌出的lbs游戏ingress。里面需要审核地理位置。然后就看到了。删了就好
